//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSHRCS.BusinessLogic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GDCabinet
    {
        public int Id { get; set; }
        public int GDId { get; set; }
        public int CabinetId { get; set; }
        public int LessonId { get; set; }
        public Nullable<int> SubstituteTeacherId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Cabinet Cabinet { get; set; }
        public virtual GroupDiscipline GroupDiscipline { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Lessons Lessons { get; set; }
    }
}
